package-lock.json
package.json
src/hookUtils.ts

chore #110 - Extract out and refactor useClickOutside hook

---

package-lock.json
package.json
src/__tests__/apiUtils.test.ts
src/apiUtils.ts

feat #113 - Refac handleAjaxErrors to handle errors that don't have response

---

package.json
src/hookUtils.ts

chore #115 - Extract out useInView to use across repos

---

package-lock.json
package.json
src/__tests__/apiUtils.test.ts
src/apiUtils.ts

chore #117 - Update handleAjaxErrors

---

package-lock.json
package.json
src/apiUtils.ts

Fix #119 - Cancelled requests being thrown as errors

---

package.json
src/constants.ts
src/hookUtils.ts

chore #121 - Extract out media selector utils

---

package-lock.json
package.json
src/generalUtils.ts
src/types.ts

chore #123 - Updates for web-onboarding

---

package.json
src/__tests__/apiUtils.test.ts
src/__tests__/generalUtils.test.ts
src/apiUtils.ts
src/generalUtils.ts
src/hookUtils.ts

fix #127 - Fix axios requestHandler not sending updated token from local storage

---

.github/workflows/codegen.yml
.github/workflows/node.js.yml
.github/workflows/npm-publish.yml
codegen.js
package-lock.json
package.json
src/constants.ts

chore #129 - Add microfrontend container constant

---

package-lock.json
package.json
src/constants.ts
src/hookUtils.ts
src/types.ts

enhancement #131 - Add keyboard shortcut constants and helper functions

---

package-lock.json
package.json
src/eventUtils.ts

enhancement #135 - Continuation after add users + teams step is done

---

package-lock.json
package.json
src/constants.ts

enhancement #137 - Continuation after add users + teams step is done

---

package.json
src/@types/can-ndjson-stream/index.d.ts
src/apiUtils.ts
src/hookUtils.ts

feat #139 - Add util for streaming API
feat #140 - Stopwatch custom hook
Closes #139
Closes #140

feat #139, #140 - Features for query builder

---

package-lock.json
package.json
src/generalUtils.ts

enhancement #142 - Add mock sleep util function

---

.github/workflows/node.js.yml
package-lock.json
package.json
src/__tests__/timeUtils.tests.ts
src/timeUtils.ts

chore #147 - Use date-fns instead of moment

---

package-lock.json
package.json
src/timeUtils.ts

Add fn to guess user's timezone offset

---

package-lock.json
package.json
src/generalUtils.ts

Add fn that gets app environment

---

package-lock.json
package.json
src/generalUtils.ts

fix #153 - getAppEnv util fn 

---

package.json
src/__tests__/generalUtils.test.ts
src/generalUtils.ts

feat #158 - Util to build browser url

---

package-lock.json
package.json
src/__tests__/hookUtils/index.test.ts
src/hookUtils.ts

feat #163 - useDebounce hook

---

package-lock.json
package.json
src/timeUtils.ts

Add fn for guessing user's timezone

---

codegen.js
package.json

chore #167 - Profile codegen

---

package-lock.json
package.json
src/timeUtils.ts

enhancement #170 - Refactor timezone utils

---

package-lock.json
package.json
src/hookUtils.ts

fix #174 - [useShortcut] Add blur event to clear first key pressed

---

package.json
src/hookUtils.ts

enhancement #176 - Allow more than 2 keys to be passed to getModifierKeys

---

package.json
src/types.ts

chore #178 - Update services enum

---

package.json
src/types.ts

chore #178 - Update notification rule service enum

---

package-lock.json
package.json
src/types.ts

enhancement #181 - Add visualize to services enum

---

package-lock.json
package.json
src/apiUtils.ts

enhancement #183 - Display entire response in error snackbar

---

package-lock.json
package.json
src/generalUtils.ts

enhancement #185 - Pluralize fn

---

package-lock.json
package.json
src/types.ts

fix #187 - Update Services enum

---

package-lock.json
package.json
src/types.ts

enhancement #189 - Add Billing to Services enum

---

package-lock.json
package.json
src/timeUtils.ts

fix #191 - Fix convertEpochToUserTimezone

---

package-lock.json
package.json
src/apiUtils.ts

fix #195 - Fix fns from useCancelRequest throwing infinite loops

---

package-lock.json
package.json
src/generalUtils.ts

enhancement #197 - Add useHoverState fn

---

package-lock.json
package.json
src/generalUtils.ts

enhancement #199 - Currency formatter

---

package.json
rollup.config.ts

fix #201 - Fix package breaking builds when imported into web-charts

---

package.json
rollup.config.ts

fix #201 - Fix web-charts build

---

package.json
rollup.config.ts

fix #201 - Remove unnecessary rollup config setting

---

package-lock.json
package.json
rollup.config.ts
src/__tests__/generalUtils.test.ts
src/generalUtils.ts

feat #205 - removeFromArrByIdx util

---

package-lock.json
package.json
src/__tests__/hookUtils/index.test.ts
src/hookUtils.ts

feat #211 - useIsJSONValid custom hook

---

package-lock.json
package.json
src/types.ts

Add Findings to Services enum

---

codegen.js
package-lock.json
package.json

chore #216 - Add preferences codegen

---

package-lock.json
package.json
src/apiUtils.ts

fix #219 - Update handleAjaxErrors for embedded errors 

---

package-lock.json
package.json
src/preferenceUtils.tsx

enhancement #222 - [Preferences] Render children after preferences have been fetched

---

package-lock.json
package.json
src/__tests__/hookUtils/index.test.ts
src/hookUtils.ts
src/preferenceUtils.tsx
src/types.ts

enhancement #226 - [Preferences] Update useTheme hook

---

package-lock.json
package.json
src/types.ts

chore #228 - Add filter keys enum

---

package-lock.json
package.json
src/generalUtils.ts

enhancement #230 - Abbreviate number

---

package-lock.json
package.json
src/types.ts

chore #232 - Add tags to filter keys

---

package-lock.json
package.json
src/types.ts

chore #236 - Add priority to filter keys

---

package-lock.json
package.json
src/generalUtils.ts

enhancement #240 - Add prettify number function

---

package-lock.json
package.json
src/generalUtils.ts
src/hookUtils.ts

enhancement #242 - Add util to process url search params

---

package-lock.json
package.json
src/constants.ts

enhancement #246 - Add util to convert filter keys to human friendly label

---

package-lock.json
package.json
src/constants.ts
src/timeUtils.ts

chore #248 - Updates for dashboard inputs

---

package-lock.json
package.json
src/generalUtils.ts

enhancement #258 - Add array processing utils

---

package-lock.json
package.json

chore #260 - Fix vulnerabilities

---

package-lock.json
package.json
src/constants.ts
src/types.ts

chore #270 - Add isCveinCisaKev to filter keys

---

package-lock.json
package.json
src/eventUtils.ts

enhancement #272 - Update event emitter types

---

package-lock.json
package.json
src/types.ts

enhancement #276 - Clone query param

---

package-lock.json
package.json
src/constants.ts

enhancement #287 - Add localStorage key for last visited custom dashboard

---

package-lock.json
package.json
src/constants.ts

enhancement #292 - Update filter label keys for isInternetExposed and isReachable

---

package-lock.json
package.json
src/hookUtils.ts

bugfix #296 - Fix resize observer error for useElementSize

---

package-lock.json
package.json
src/types.ts

chore #299 - Readonly enum

---

package-lock.json
package.json
src/types.ts

chore #301 - Add $assetSources to FilterKeys

---

package-lock.json
package.json
src/types.ts

chore #301 - Add $assetDeleted to FilterKeys

---

package-lock.json
package.json
rollup.config.ts
src/apiUtils.ts
src/generalUtils.ts
src/timeUtils.ts

Closes #304
- axios
- axios-retry
- date-fns
- date-fns-tz
- uuid
- @json2csv/plainjs

chore #304 - Bump package versions

---

package-lock.json
package.json
src/constants.ts

chore #306 - "os" filter key label incorrect processing

---

package-lock.json
package.json
src/types.ts

chore #323 - Add settings to services enum

---

package-lock.json
package.json
src/generalUtils.ts

enhancement #329 - Scroll selection into view
